### PR TITLE
Add support for testmode

### PR DESCRIPTION
**Pull request by Jellyfrog**

### CODE REVIEW

**Comment by greydnls** [comment]
This is wonderful. Can you add test coverage and I will gladly merge.

**Comment by Jellyfrog** [comment]
Will do

**Comment by Jellyfrog** [comment]
Is it ok to do like this @kayladnls?
Else I can change it back to `protected` and hardcode the urls in the test

**Comment by greydnls** [comment]
I was thinking more along the lines of this: https://github.com/thephpleague/omnipay-common/blob/e8cdb1b7e3779bf945a3573803358d902db3267c/tests/Omnipay/Common/Message/AbstractRequestTest.php#L259-L268

Just to test that test mode is getting set correctly. 

And then you can hardcode the URLs to ensure that when test mode is set, the right endpoint is called. I'd prefer those endpoints to be protected so they can't be changed.

**Comment by Jellyfrog** [comment]
Its what it did, but dynamically? Well I changed to protected and hardcoded urls now.

**Comment by Jellyfrog** [comment]
@kayladnls ping...

**Pull request merged**
