### PR TITLE
Adding purchase status support

### PR DESCRIPTION
**Pull request by Jellyfrog**
Not really sure what to name the function (`purchaseStatus`), any input?
I also created a proposal to add it to the interface; https://github.com/thephpleague/omnipay/issues/355

Ping @delatbabel @kayladnls

### CODE REVIEW

**Comment by delatbabel** [comment]
getPurchaseStatus() would seem to make sense to me.

**Comment by Jellyfrog** [comment]
@delatbabel changed it

**Comment by delatbabel** [comment]
Merged. Please test that there are no issues in production then I will tag.

**Comment by Jellyfrog** [comment]
Works fine!

**Pull request merged**
